### ISSUE TITLE
Cannt set bar backgroundColor 

### ISSUE THREAD

**Issue by lecourtb** [zibous/lovelace-graph-chart-card#3]
Hello, very promizing lovelace card !
But in the bar chart example you give "Makro Nährstoffe", I cannot change background colors of bars.

I tried:

```
- type: 'custom:chart-card'
  title: 'Makro Nährstoffe'
  icon: 'mdi:nutrition'
  chart: 'bar'
  chartOptions:
    plugins:
      title:
        display: true
        text: 'Aufteilung Nährstoffe (kal) pro Tag'
        color: '#ff9500'
  entities:
    - entity: sensor.consommation_pac_current_a
      name: Eiweis
    - entity: sensor.consommation_pac_current_b
      style:
        backgroundColor: '#FF0000'
      name: Fett
    - entity: sensor.consommation_pac_current_c
      name: Kohlenhydrate
```

backgroundColor is not taken into account.
Thanks in advance !

**Comment by zibous** [comment]
Sorry for the late reply, I was on vacation in Asia and barely had internet. Try this setting:

<img width="545" alt="Bildschirmfoto 2024-04-01 um 17 42 53" src="https://github.com/zibous/lovelace-graph-chart-card/assets/30198737/aa1db75d-71e4-4397-b6b0-f734dca8df93">


```
   - type: custom:chart-card
     title: Makro Nährstoffe
     icon: mdi:nutrition
     chart: bar
     height: 320
     chartOptions:
       segmented: true
       plugins:
         title:
           display: true
           text: Aufteilung Nährstoffe (kal) pro Tag
       scales:
         'y':
           title:
             display: true
             text: Kalorien
     entities:
       - options:
           unit: kal
       - entity: sensor.peter_eiweis_makronahrstoff
         name: Eiweis
         style:
           backgroundColor: '#FDD835'
       - entity: sensor.peter_fett_makronahrstoff
         name: Fett
         style:
           backgroundColor: '#e74c3c'
       - entity: sensor.peter_kohlenhydrate_makronahrstoff
         name: Kohlenhydrate
         style:
           backgroundColor: '#009688'
```
Your settings:
<img width="545" alt="Bildschirmfoto 2024-04-01 um 17 40 18" src="https://github.com/zibous/lovelace-graph-chart-card/assets/30198737/fe127989-01dd-4aa4-a492-e90431468c05">
