### ISSUE TITLE
Manual installing - I don't see the card

### ISSUE THREAD

**Issue by moritzmaier84** [zibous/lovelace-graph-chart-card#4]
Copied the files in my community folder.
Added the resource (new place, seems like this step here is older).

But I cannot see the card, though.

Is it still possible to use oder too old?
Any ideas?

**Comment by zibous** [comment]
there is mo visual editor available for type 'custom:chart-card', it is only possible via manual configuration.

- Reload resources 
- Edit dashboard 
- New Card 
- Add Manually

Example:
```
type: 'custom:chart-card'
title: Temperaturverlauf
icon: 'mdi:fire'
height: 320
chart: line
showstate: true
chartOptions:
  plugins:
    legend:
      display: false
entities:
  - options:
      unit: °C
      borderWidth: 1
  - entity: sensor.temp_sensor_temperature_aussen
    name: Aussen
    style:
      fill: true
      gradient:
        colors:
          - '#03a9f4'
          - '#00bcd4'
          - '#8bc34a'
          - '#e51400'
          - '#cddc39'
          - '#ff9800'
          - '#ff5722'
```

<img width="985" alt="Bildschirmfoto 2024-05-19 um 11 30 39" src="https://github.com/zibous/lovelace-graph-chart-card/assets/30198737/4f712d74-5d4b-494d-8db1-9f47288cac5d">
