### ISSUE TITLE
How to ADD différent color ?

### ISSUE THREAD

**Issue by barto95** [zibous/lovelace-graph-chart-card#5]
Hi thank's for the card

just a question, how to add multiple entity with group by label ?

example chart used for note school of child and I want to have a radar color blue for average score child and radar color Red for average score classroom

**Comment by zibous** [comment]
> just a question, how to add multiple entity with group by label ?
> 
> example chart used for note school of child and I want to have a radar color blue for average score child and radar color Red for average score classroom

Radar Chart is simple, can only use one data series for the chart.

```
- type: 'custom:chart-card'
  title: Test
  icon: 'mdi:weight-lifter'
  chart: radar
  entities:
    - entity: sensor.data1
    - entity: sensor.data2
    - entity: sensor.data3
    - entity: sensor.data4
```

see: https://github.com/zibous/lovelace-graph-chart-card/blob/main/docs/getting-started/chart-types/radarchart.md
